# Generated by Django 4.2.7 on 2023-11-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peleta',
            new_name='Paleta',
        ),
    ]
