# Generated by Django 4.2.7 on 2023-12-04 23:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_peleta_paleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paleta',
            name='formato',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
