# Generated by Django 4.2.7 on 2023-11-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Automovil',
            new_name='Auto',
        ),
    ]
