# Generated by Django 4.2.7 on 2023-12-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovil', '0002_rename_automovil_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='descripcion',
            field=models.TextField(max_length=50),
        ),
    ]
